### ISSUE TITLE
Allow to terminate workers asynchronously

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/rush#3]
At the moment there's a function to terminate all workers, but I can't tell workers that after the current batch of jobs is done they can terminate. This is important when running on a cluster, where I don't want to have lots of workers doing nothing and consuming resources because one worker isn't done.

Could be implemented through an optional argument to `$push_tasks()` for example to indicate that when these tasks are done, the workers should be terminated. Then a worker that doesn't have work anymore can shut down even if there are still other workers running.

**Comment by be-marc** [comment]
Solved in #9.
